kind: pipeline
name: default

steps:
  - name: build
    image: docker
    commands:
      - docker build . -t toukan:latest
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: deploy preview
    image: docker/compose:1.24.1
    volumes:
        - name: docker
          path: /var/run/docker.sock
    commands:
      - docker-compose -p toukan up -d preview


  - name: deploy production
    image: docker/compose:1.24.1
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker-compose -p toukan up -d production
    when:
      branch:
        - master

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
