kind: pipeline
name: default

steps:
  - name: build preview
    image: docker/compose:1.24.1
    commands:
      - docker-compose -p toukan build preview
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: deploy preview
    image: docker/compose:1.24.1
    volumes:
        - name: docker
          path: /var/run/docker.sock
    commands:
      - docker-compose -p toukan up -d preview

  - name: build production
    image: docker/compose:1.24.1
    commands:
      - docker-compose -p toukan build production
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      branch:
        - master

  - name: deploy production
    image: docker/compose:1.24.1
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker-compose -p toukan up -d production
    when:
      branch:
        - master

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
