kind: pipeline
type: docker
name: default

steps:
#  - name: eslint check
#    image: node:14-alpine
#    commands:
#      - yarn --network-timeout 3600000
#      - yarn lint
  - name: build preview
    image: docker/compose:1.24.1
    commands:
      - docker-compose -p toukan build preview
    volumes:
      - name: docker
        path: /var/run/docker.sock
#    depends_on:
#      - clone

  - name: deploy preview
    image: docker/compose:1.24.1
    volumes:
        - name: docker
          path: /var/run/docker.sock
    commands:
      - docker-compose -p toukan up -d preview
    depends_on:
      - build preview

  - name: build production
    image: docker/compose:1.24.1
    commands:
      - docker-compose -p toukan build production
    volumes:
      - name: docker
        path: /var/run/docker.sock
    depends_on:
      - clone
    when:
      branch:
        - master

  - name: deploy production
    image: docker/compose:1.24.1
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker-compose -p toukan up -d production
    depends_on:
      - build production
    when:
      branch:
        - master
      ref:
        - refs/tags/*

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
