version: '3'
services:
  preview:
    build:
      context: .
      args:
        PUBLIC_DIR: "https://toukan.cchampou.me/"
    image: toukan:latest
    restart: always
    labels:
      - "traefik.frontend.rule=Host:toukan.cchampou.me"
      - "traefik.frontend.auth.basic.users=cchampou:$$apr1$$RSwa8YGS$$IqFhDNJhBOiWQMWLq3phQ1,remi:$$apr1$$5103mRGO$$claAyjKFmuRZrOG1O6qZu0"
      - "traefik.backend.port=3000"
      - "traefik.enable=true"
      - "traefik.docker.network=layko_layko_net"
  production:
    build:
      context: .
      args:
        PUBLIC_DIR: "https://toukancinemalyon.fr/"
    image: toukan:latest
    restart: always
    labels:
      - "traefik.frontend.rule=Host:toukancinemalyon.fr,www.toukancinemalyon.fr"
      - "traefik.backend.port=3000"
      - "traefik.enable=true"
      - "traefik.docker.network=layko_layko_net"

networks:
  default:
    external:
      name: layko_layko_net
