version: '3'
services:
  preview:
    build:
      context: .
      args:
        PUBLIC_DIR: "https://toukan.cchampou.me/"
    image: toukan:latest
    restart: always
    labels:
      - traefik.http.routers.toukan-preview.rule=Host(`toukan.cchampou.me`)
      - traefik.http.routers.toukan-preview.tls=true
      - traefik.http.routers.toukan-preview.tls.certresolver=main
  production:
    build:
      context: .
      args:
        PUBLIC_DIR: "https://toukancinemalyon.fr/"
    image: toukan:latest
    restart: always
    labels:
      - traefik.http.routers.toukan.rule=Host(`toukancinemalyon.fr`)
      - traefik.http.routers.toukan.tls=true
      - traefik.http.routers.toukan.tls.certresolver=main

networks:
  default:
    external:
      name: allixo_default
